name: .NET

on:
  push:
    branches:
      - '**'

jobs:
  reusable_workflow_job:
    uses: HBDStack/ShareWorkflows/.github/workflows/dotnet-package-release.yml@main
    with:
      Project_Path: 'HBDStack.Framework.sln'
      Enable_Release: ${{ github.ref == 'refs/heads/main' }}
      Enable_Nuget_Release: ${{ github.ref  == 'refs/heads/main'}}
